apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 4
  template:
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        ports:
        - containerPort: 8080
