apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../kustomize-guestbook

tst-konfig:
  - target:
      version: v1
      kind: Deployment
      name: guestbook-ui
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 4
      - op: replace
        path: /spec/template/spec/containers/name
        value: guestbook-ui-tprodst