apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: native-ic-ingress-class
spec:
  controller: oci.oraclecloud.com/native-ingress-controller
  parameters:
    namespace: guestbook-tst
