apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../kustomize-guestbook

patches:
  - target:
      version: v1
      kind: Deployment
      name: guestbook-ui
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: guestbook-ui-tst
  - path: ingressclass.yaml
    target:
      kind: IngressClass
      name: native-ic-ingress-class
  - path: ingressclassparameters.yaml
    target:
      kind: IngressClassParameters
      name: native-ic-params
  - path: ingress.yaml
    target:
      kind: Ingress
      name: native-ic-ingress