apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../kustomize-guestbook

patches:
  - target:
      version: v1
      kind: Deployment
      name: guestbook-ui
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: guestbook-ui-uat